In [5]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
a

print(a.ndim)
print(a.shape)
a.dtype

2
(2, 3)


dtype('float32')

In [19]:
arraythree=np.array([[[1,2,2],[3,4,2]],[[5,6,2],[5,6,2]]],dtype=np.float32)
print(arraythree.ndim)
arraythree.ndim

3


3

In [18]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
test=np.array([],ndmin=6)
test

array([], shape=(1, 1, 1, 1, 1, 0), dtype=float64)

In [29]:
test2=np.array([1],ndmin=6)
test2

array([[[[[[1]]]]]])

In [33]:
test3=np.array([[[1,2,2],[3,4,2]],[[5,6,2],[5,6,2]]],ndmin=6)
test3

array([[[[[[1, 2, 2],
           [3, 4, 2]],

          [[5, 6, 2],
           [5, 6, 2]]]]]])