In [4]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a)
print(a.shape)
b=a.reshape(3,2)

[1 2 3 4 5 6]
(6,)


In [5]:
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
c=a.reshape(2,-1)
# -1 is placeholder, telling python to do the math and figure it out

In [7]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
d = a.ravel()
d

# ravel() will flatten an array

array([1, 2, 3, 4, 5, 6])

In [10]:
# transposing
e=np.arange(10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
f=c.T
f
# T is for transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
g=c.transpose((1,0))
g
# tranpose works similarly to T but you can define axes
# T transposes the first two axes

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
g [1,1]

5

In [15]:
g[1,-1]

5

In [17]:
g[0,:] # first row

array([1, 4])

In [18]:
g[:,0] # first column

array([1, 2, 3])

In [20]:
a = list(range(10))
print(a)
a[:3]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


[0, 1, 2]

In [38]:
asdf=np.array(range(2,11))
print(asdf)

xx=asdf.reshape(3,3)
print(xx)

yy=np.sqrt(xx)
yy

[ 2  3  4  5  6  7  8  9 10]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


array([[1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766]])