### Homework 3 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into an numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [1]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


1. How can you get help on `np.array`?

Call dir() on np.array.

Call dir() on car.

Note the difference. `car` has methods and attributes we can use.

In [10]:

# help(np.array)  # returns functionality of np.array
# dir(np.array)   # returns list of attributes for np.array
# dir(car)        # returns list of attributes for car

 2.What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [33]:
print(car.dtype)
car2=car.astype(str) #unicode
print(car2.dtype)

print(mpg.dtype)
print(horsepower.dtype)

print(origin.dtype)
origin2=origin.astype(str)  #unicode
print(origin2.dtype)

object
<U36
float64
float64
object
<U6


3.`numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [ ]:
# This is called an alias
# We would import as an alias to shorten "numpy" to "np"
    # This is quicker to type
    # This particular 'np' is conventionally used

4.Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [42]:
print(car.ndim)
print(mpg.ndim)
print(cylinders.ndim)
# These arrays have 1 dimension, use .ndim to show this
    # ndim is number of dimensions
    # print() the name_of_array.ndim


1
1
1


5.Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [49]:
# mpg*2
# mpg/3
# mpg**4
# np.sqrt(mpg)

6.What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [60]:
from scipy import stats
print(np.sum(horsepower))
print(np.min(horsepower))
print(np.max(horsepower))
print(np.median(horsepower))
print(stats.mode(horsepower))

42033.0
0.0
230.0
93.5
ModeResult(mode=array([150.]), count=array([22]))


7.Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [65]:
first_five=acceleration[0:5]
print(first_five)

every_other=acceleration[0::2]  # slicing [start:stop:step]
print(every_other)

[12.  11.5 11.  12.  10.5]
[12.  11.  10.5  9.  10.  17.5 11.  11.   8.   9.5 15.  15.5 14.5 17.5
 17.5 15.  15.  18.5 15.5 19.  13.  15.5 15.5 11.5 13.  12.  13.5 15.
 14.  19.5 19.  19.  15.5 23.5 16.5 12.  13.  11.  13.5 13.5 14.  14.
 18.  18.  17.  15.  13.  13.  12.5 12.  14.5 11.  16.5 16.  16.  14.
 13.  15.  19.5 13.5 14.  13.  19.5 14.  11.  13.5 16.5 16.  19.  21.
 17.  16.5 14.5 16.  16.5 14.5 19.  15.5 15.  16.  16.  19.5 14.  13.5
 18.5 19.  13.5 16.  16.  13.5 17.  14.  15.  14.5 17.5 16.9 17.7 13.
 13.9 15.4 17.6 22.2 14.2 17.7 16.2 12.2 16.4 15.7 21.9 16.7 12.  14.
 14.8 15.5 12.5 13.7 16.4 17.7 11.1 12.2 14.5 18.2 17.  16.4 14.5 13.5
 14.4 18.6 15.5 12.8 18.2 15.4 17.2 16.7 15.1 13.4 13.7 14.2 14.5 16.7
 14.9 13.6 15.8 16.6 18.2 18.2 15.4 13.2 14.9 15.  14.  14.4 20.1 24.8
 13.2 19.2 16.  12.9 14.7 15.5 16.5 20.1 15.8 17.5 15.2 14.4 21.7 19.9
 13.8 18.  11.4 15.1 17.  16.4 12.6 16.9 16.1 19.4 16.  16.2 14.2 14.4
 14.8 20.4 19.6 13.8 19.  16.6 18.6 16.2 18.  20.5 18.2 

8.Show how to select the number `99` in the array below. 

In [19]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])

In [70]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])
select_99[1][2]

99

9.Select the last element in each subarray (do this with one operation.)

In [21]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

In [86]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
select_more[:,2]

array([3, 6, 9])

10.Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [95]:
# np.lookfor("log")
# np.lookfor(np.log)
np.log(mpg)

C:\Users\Sarah\AppData\Local\Temp/ipykernel_10772/3512358094.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(mpg)


array([2.89037176, 2.7080502 , 2.89037176, 2.77258872, 2.83321334,
       2.7080502 , 2.63905733, 2.63905733, 2.63905733, 2.7080502 ,
             -inf,       -inf,       -inf,       -inf,       -inf,
       2.7080502 , 2.63905733,       -inf, 2.7080502 , 2.63905733,
       3.17805383, 3.09104245, 2.89037176, 3.04452244, 3.29583687,
       3.25809654, 3.21887582, 3.17805383, 3.21887582, 3.25809654,
       3.04452244, 2.30258509, 2.30258509, 2.39789527, 2.19722458,
       3.29583687, 3.33220451, 3.21887582, 3.21887582,       -inf,
       2.94443898, 2.77258872, 2.83321334, 2.94443898, 2.89037176,
       2.63905733, 2.63905733, 2.63905733, 2.63905733, 2.48490665,
       2.56494936, 2.56494936, 2.89037176, 3.09104245, 2.94443898,
       2.89037176, 3.13549422, 3.33220451, 3.40119738, 3.40119738,
       3.4339872 , 3.55534806, 3.29583687, 3.25809654, 3.17805383,
       3.21887582, 3.13549422, 2.99573227, 3.04452244, 2.56494936,
       2.63905733, 2.7080502 , 2.63905733, 2.83321334, 2.39789

11.You your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [26]:
#type(origin)
origin_test = [0,6,5,0,6,5]


array([0, 5, 6])

12.
- Create a 2D array and print its shape as well as ndim. (Any shape is fine)

- Create a 3D array and print its shape as well as ndim.

- Create a 4D array and print its shape as well as ndim. *It's hard to visualize 4-Dimensions but numpy can do it with ease!*

In [122]:
two_array=np.array([[1,1,1,1,1,1],[2,2,2,2,2,2]])
# print(two_array)
print(two_array.shape)
print(two_array.ndim)

three_array=np.zeros((3,2,6))
# print(three_array)
print(three_array.shape)
print(three_array.ndim)

four_array=np.array([1,2,3,4],ndmin=4)
# print(four_array)
print(four_array.shape)
print(four_array.ndim)


(2, 6)
2
(3, 2, 6)
3
(1, 1, 1, 4)
4


13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [162]:
# try1=np.array('US' in origin)
# print(try1)
# print(type(try1))

# try2=(str(origin).str.contains("US"))
# print(try2)

# try3=origin=="US"
# print(type(try3[0]))
# print(try3)

origin=="US"

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False, False, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False,

14.Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [158]:
car[origin=="US"]

array(['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
       'Plymouth Satellite', 'AMC Rebel SST', 'Ford Torino',
       'Ford Galaxie 500', 'Chevrolet Impala', 'Plymouth Fury iii',
       'Pontiac Catalina', 'AMC Ambassador DPL',
       'Chevrolet Chevelle Concours (sw)', 'Ford Torino (sw)',
       'Plymouth Satellite (sw)', 'AMC Rebel SST (sw)',
       'Dodge Challenger SE', "Plymouth 'Cuda 340",
       'Ford Mustang Boss 302', 'Chevrolet Monte Carlo',
       'Buick Estate Wagon (sw)', 'Plymouth Duster', 'AMC Hornet',
       'Ford Maverick', 'AMC Gremlin', 'Ford F250', 'Chevy C20',
       'Dodge D200', 'Hi 1200D', 'Chevrolet Vega 2300', 'Ford Pinto',
       'AMC Gremlin', 'Plymouth Satellite Custom',
       'Chevrolet Chevelle Malibu', 'Ford Torino 500', 'AMC Matador',
       'Chevrolet Impala', 'Pontiac Catalina Brougham',
       'Ford Galaxie 500', 'Plymouth Fury iii', 'Dodge Monaco (sw)',
       'Ford Country Squire (sw)', 'Pontiac Safari (sw)',
       'AMC Hornet Sportabout (

15.Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 

In [ ]:
# An np.array is preferred
    # to use less memolry
    # to use arithmetic operations
# A python list is preffered
    # to use different sizes of nested data
    # to use different data types

16.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

In [176]:
idmatrix=np.identity(5)
# idmatrix=np.identity(5,dtype="str")
print(idmatrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


17.Transpose the following array. 

In [ ]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])


In [172]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])


np.transpose(transpose_me)
# transpose_me.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

1.Why does this multiplication operation fail? 

In [ ]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2

Use numpy to answer the following questions. 

2.What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

3.On average are Japanse cars more fuel efficient than US cars? 

4.What is the correlation coefficient of `mpg` and `weight`? What is a correlaton coefficient?